logging:
  level:
    org.hibernate.SQL: DEBUG

spring:
  application:
    name: "my-jpa-work"
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/my_jpa_work
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: none
      #ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always
